name: Code Convention Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  lint_and_format_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64
          cache: pip
          cache-dependency-path: "**/requirements.txt"

      - name: Install ruff and black
        run: |
          python -m pip install --upgrade pip
          pip install ruff black black[jupyter]

      - name: Ruff lint
        run: ruff --output-format=github .

      - name: Black format check
        run: black --check .
